name: CascoStation
favicon: null
layout_spectrum: 0.01356
typography_spectrum: 0.24641
title: CascoStation Coworking
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fafafa'
    - '#88653f'
    - '#e89a35'
    - '#78a199'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.9922086966689676
  rhythmicContrast: 0.25
purpose: []
